### ISSUE TITLE
Just why?

### ISSUE THREAD

**Issue by threattt** [vani42069/Pet-cheat-detector#3]
Why do we need this mod? plz Delete it ... Make then Toolbox detector ... vani42069 why do you need this garbage?

**Comment by Zezo12345** [comment]
Maybe drama with a specific proxy mod developer who developed the original partner replacer. Other than that there are exploit mods everywhere i get your point there is no point for this.

**Comment by vani42069** [comment]
Just dont cheat? 4head

**Comment by xiphion** [comment]
@threattt @Zezo12345 don't worry, yall cheaters will get banned either way ^_^

**Comment by ghost** [comment]
cheaters NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOB

**Comment by Owyn** [comment]
SP detector when? Maybe I should write one... 🤔

**Comment by vani42069** [comment]
Owyn youre saying something but all that comes out on my screen is written monkey noises

**Comment by ghost** [comment]
UHUHUHUHUHUHUHUHUHUHUHUHUHUHUHUHUHUHU

**Comment by Zezo12345** [comment]
dont @ me @iribae , this mod is made due to personal drama, i dont see fish bot detector for example or cs teleport detector or pit of pitrax teleporter detector or dungeon last boss teleport and other exploits that are too many to make a list of which are publicly accessible. For your information almost everyone i know used fish bot, dont act innocent like you never used it. I mean even bern sells bot exploit scripts. I dont get your point, if someone has a drama with someone else he better solve that drama face to face privately.  Although this is github you are free to do whatever you want exploit or not.

**Comment by Kuroine** [comment]
PARTNER REPLACER OMEGALUL

**Comment by ghost** [comment]
@Zezo12345 hoes mad

**Comment by Leyki** [comment]
@Zezo12345 pepega

**Comment by vani42069** [comment]
Hoes mad

**Comment by Snugglez** [comment]
@Zezo12345 this mod was made regardless of the retards previously spreading the exploit on GitHub, as for your other examples, there really isn't an easy method for detecting those as an external character, especially for instanced things like pit. This mostly exists cause it is extremely easy to detect packet wise

**Comment by Leyki** [comment]
@Zezo12345 tagging so you hopefully don't miss Snug's comment!

**Comment by codeagon** [comment]
Infringes on my God given right to cheat. You should be ashamed. Bleas delete or youll be hearing fronms jehdmy loqyrers

**Comment by Patricktheorge** [comment]
Bot public when?

**Comment by Zezo12345** [comment]
Rename this title to meme channel or something. Why many devs posting here lmao smh.

**Comment by Kuroine** [comment]
@vani42069 why you not letting me cheat?!

**Comment by vani42069** [comment]
Okay closing this you goofy ass cheaters

**Comment by Kasea** [comment]
Hi vani big fan

**Comment by IM02** [comment]
Hi vani

**Comment by ghost** [comment]
Rodrigo.



Rodrigo.

**Comment by xiphion** [comment]
Rodrigo Santoro, beng's best friend?
